### ISSUE TITLE
November 2023 Meeting Topics

### ISSUE THREAD

**Issue by nickfarrow** [MelbourneBitDevs/meetup#12]
Link anything you'd like to discuss: news, demos, ideas, whatever!

**Comment by nickfarrow** [comment]
"OP threw a 5"

https://www.reddit.com/r/coldcard/comments/17epqk8/040_bitcoin_taken_instantly_from_my_coldcard/

**Comment by nickfarrow** [comment]
How to setup a Bitcoin Air-Gap Computer? DON'T
https://airgapcomputer.com/

**Comment by nickfarrow** [comment]
First mainnet transaction having a Blake3 hash lock implemented in Bitcoin Script
https://twitter.com/robin_linus/status/1721969594686926935

**Comment by nickfarrow** [comment]
Swan Bitcoin to Stop Serving Customers Interacting with Privacy Services
https://www.nobsbitcoin.com/swan-bitcoin-privacy-update/

**Comment by nickfarrow** [comment]
Flockstr: Meetup on Nostr
https://www.flockstr.com/

**Comment by nickfarrow** [comment]
Tapleaf Circuits demo (with SHA256)
https://techmix.github.io/tapleaf-circuits/

**Comment by nickfarrow** [comment]
Review technical bitcoin transcripts and earn sats
https://twitter.com/adamcjonas/status/1725247716425675002

**Comment by nickfarrow** [comment]
OP Codes Explained
https://opcodeexplained.com/

**Comment by nickfarrow** [comment]
BitStream: Decentralized File Hosting Incentivised via Bitcoin Payments
https://bitvm.org/bitvm.pdf

**Comment by nickfarrow** [comment]
Six OFAC-sanctioned transactions missing from blocks
https://twitter.com/0xB10C/status/1726964430460588201
https://twitter.com/satofishi/status/1727166867620741367

**Comment by ttiiggss** [comment]
The Cyberspace Meta-Protocol: An Extension of Reality
https://github.com/arkin0x/cyberspace
https://github.com/arkin0x/ONOSENDAI
https://www.onosendai.tech/

**Comment by nickfarrow** [comment]
BushBash & Australia-wide bitdevs site
https://github.com/MelbourneBitDevs/bitdevs.com.au/pull/20

**Comment by archer0nt** [comment]
OCEAN - non-custodial mining pool
https://ocean.xyz/

**Comment by nickfarrow** [comment]
83.7 BTC Fee

https://mempool.space/tx/b5a2af5845a8d3796308ff9840e567b14cf6bb158ff26c999e6f9a1f5448f9aa
https://twitter.com/83_5BTC/status/1728873072349069352

**Comment by nickfarrow** [comment]
Binance settlement with Justice Department

https://www.cnbc.com/2023/11/22/whats-next-for-binance-after-doj-settlement-departure-of-changpeng-zhao.html

**Comment by nickfarrow** [comment]
Wallet of Satoshi withdraws from US
https://twitter.com/walletofsatoshi/status/1727937085741678679

**Comment by nickfarrow** [comment]
BDK Coin Select
https://github.com/bitcoindevkit/coin-select/

**Comment by nickfarrow** [comment]
Beechworth BushBash
https://bitcoinbushbash.info/
