### ISSUE TITLE
December 2023 Meeting Topics

### ISSUE THREAD

**Issue by nickfarrow** [MelbourneBitDevs/meetup#15]
Link anything you'd like to discuss: news, demos, ideas, whatever!

**Comment by nickfarrow** [comment]
Just noticed we missed this one from @ttiiggss last meeting:

The Cyberspace Meta-Protocol: An Extension of Reality
https://github.com/arkin0x/cyberspace
https://github.com/arkin0x/ONOSENDAI
https://www.onosendai.tech/

**Comment by brrrcode** [comment]
We discussed the descriptor format on the seedhammer and I came across this tweet. Good follow up
https://x.com/seedhammer/status/1731949704210956663

**Comment by nickfarrow** [comment]
OCEAN not including inscriptions in blocks
https://twitter.com/ocean_mining/status/1732207450114162855

**Comment by nickfarrow** [comment]
BIPS resource
http://bips.xyz/

**Comment by smolgrrr** [comment]
Submitted a solo-mining app to the Umbrel app-store. I'll demo it with a nerd-miner at the next meet-up. This thursday?

https://github.com/getumbrel/umbrel-apps/pull/915

**Comment by ttiiggss** [comment]
rot13maxi creates a script that removes ordinals from your node.

https://bitcoinnews.com/taproot-wizards-script-block-ordinals-inscriptions/
https://github.com/rot13maxi/bitcoin-purifier

**Comment by ttiiggss** [comment]
Mt Gox starts payouts

https://bitcoinnews.com/mt-gox-payouts-started-after-10-years/

**Comment by ttiiggss** [comment]
Alternative AI that doesn't rely on VC/Big Tech

https://unleashed.chat/
https://chat.plebai.com/
https://openagents.com/ (a continuation of gputopia.ai)
