### ISSUE TITLE
 January 2024 Meeting Topics

### ISSUE THREAD

**Issue by ttiiggss** [MelbourneBitDevs/meetup#16]

**Comment by ttiiggss** [comment]
Ordinals Are An Attack On Bitcoin, But Not How You Think They Are!

https://www.youtube.com/watch?v=-RswZDQTqsI
ties in with the BCH + BSV hard fork enthusiasts and also Neo blockchain involvement which links to the CCP.

**Comment by ttiiggss** [comment]
### The world’s first Bitcoin-centric Ai
Chat, code, produce content, ask and learn about Bitcoin.

https://www.spiritofsatoshi.ai/

Also is [unleashed](https://unleashed.chat) and [plebai](https://chat.plebai.com/)

**Comment by ttiiggss** [comment]
### Atomicals Theory and Digital Objects on Bitcoin

[documentation](https://docs.atomicals.xyz/) (the degens are selling ARC-20 tokens for... ALOT.) 

[current price of bullshit tokens](https://unisat.io/atomicals/market/arc20)

**Comment by thomasWos** [comment]
**Bitcoin Layer 2 - Bitfinity**

EVM-compatible
Mainnet launch late January or early February

https://bitfinity.network/
https://decrypt.co/212411/bitfinity-aims-to-enhance-bitcoin-ordinals-with-ethereum-virtual-machine-integration-on-icp

**Comment by BBlackwo** [comment]
From J9: Covenants and OPCTV

**Comment by BBlackwo** [comment]
[Phoenix wallet adds ability to request inbound liquidity](https://www.nobsbitcoin.com/phoenix-wallet-android-v2-1-0/)
