### ISSUE TITLE
Beechworth Bush Bash 2024 Meeting Topics

### ISSUE THREAD

**Issue by BBlackwo** [MelbourneBitDevs/meetup#18]
On the Friday afternoon of the [Beechworth Bush Bash](https://bitcoinbushbash.info/) we're having BitDevs!

Link to anything you'd like to discuss: news, demos, ideas, whatever!

**Comment by BBlackwo** [comment]
It's always fun to dunk on Coinbase 😁
https://www.nobsbitcoin.com/coinbase-restabilized-after-heavy-traffic-causes-issues/

**Comment by BBlackwo** [comment]
Discussion on Covenants: OP_VAULT, OP_CTV, and many more 😅

What are the risks, benefits, use cases, etc

- https://bitcoinops.org/en/topics/covenants/
- https://blog.keys.casa/why-bitcoin-needs-covenants/

**Comment by BBlackwo** [comment]
Samourai releases https://nextblock.is

- https://code.samourai.io/dojo/one-dollar-fee-estimator-js/-/tree/master/packages/estimator 
- https://code.samourai.io/oxt/one_dollar_fee_estimator/-/blob/master/README.md

**Comment by BBlackwo** [comment]
UTXO management in a high fee environment

https://unchained.com/blog/small-utxo-bitcoin-dust/

**Comment by BBlackwo** [comment]
New Twenty Two Portal NFC hardware wallet

https://twitter.com/afilini/status/1766085500106920268

**Comment by BBlackwo** [comment]
Bitcoin Open Source Development Report 2023

https://www.nobsbitcoin.com/bitcoin-developers-report-2023/

**Comment by BBlackwo** [comment]
Roman Sterlingov Found Guilty on Four Counts, Court Finds Chainalysis 'Reliable'

https://www.nobsbitcoin.com/roman-sterlingov-found-guilty-on-four-counts/

**Comment by BBlackwo** [comment]
BISQ v2 test release 

https://www.nobsbitcoin.com/bisq2-v0-0-7/

**Comment by BBlackwo** [comment]
Craig is not Satoshi 😜

https://www.nobsbitcoin.com/craig-wright-is-not-satoshi-says-judge/

**Comment by ttiiggss** [comment]
Just found this Whitepaper, might be relevant.

https://bitkey.build/content/files/2023/11/Bitkey-Recovery-Features.pdf

**Comment by nickfarrow** [comment]
Marathon Transaction Accelerator: Slipstream
https://ir.mara.com/news-events/press-releases/detail/1343/marathon-digital-holdings-launches-slipstream
