### ISSUE TITLE
March 2024 Meeting Topics

### ISSUE THREAD

**Issue by nickfarrow** [MelbourneBitDevs/meetup#20]
Link anything you'd like to discuss: news, demos, ideas, whatever!

**Comment by nickfarrow** [comment]
Marathon Transaction Accelerator: Slipstream
https://ir.mara.com/news-events/press-releases/detail/1343/marathon-digital-holdings-launches-slipstream

**Comment by BBlackwo** [comment]
Phoenix Server! https://twitter.com/PhoenixWallet/status/1771236080680841668

**Comment by nickfarrow** [comment]
UmbrelOS 1.0
https://umbrel.com/umbrelos

**Comment by nickfarrow** [comment]
Machankura 2.0: Turning phones into hardware wallets
https://www.coindesk.com/consensus-magazine/2024/03/18/machankura-20-turning-feature-phones-into-bitcoin-hardware-wallets/

**Comment by nickfarrow** [comment]
GoFetch: Unpatchable vulnerability in Apple M1 chip leaks secret encryption keys
https://arstechnica.com/security/2024/03/hackers-can-extract-secret-encryption-keys-from-apples-mac-chips/

**Comment by nickfarrow** [comment]
Marathon mining pool makes art through transaction ordering
https://mempool.space/block/0000000000000000000341cc26cda4af82cd25f7063c448772228cbf2836915b?audit=false

**Comment by nickfarrow** [comment]
Bitcoin Halving Party & Launch of Victorian Bitcoin Technology Club

https://vbtc.org.au/halving-event

**Comment by nickfarrow** [comment]
Fedi Bravo (beta)
https://www.fedi.xyz/blog/fedi-bravo-is-here

**Comment by BBlackwo** [comment]
Hedgehog: A new Layer 2 protocol. https://www.nobsbitcoin.com/introducing-hedgehog/
