### ISSUE TITLE
April 2024 Meeting Topics

### ISSUE THREAD

**Issue by nickfarrow** [MelbourneBitDevs/meetup#21]
Link anything you'd like to discuss: news, demos, ideas, whatever!

**Comment by thomasWos** [comment]
![telegram-cloud-photo-size-5-6068963990010182202-y](https://github.com/MelbourneBitDevs/meetup/assets/785740/21d4a55b-ce69-4d7e-8282-a7c3db88377e)

**Comment by nickfarrow** [comment]
ViaBTC Pool Bug Disclosure, rewarded with relatively tiny bounty
https://b10c.me/blog/012-viabtc-spv-vulnerability-disclosure/

**Comment by nickfarrow** [comment]
Unpatchable vulnerability in Apple chips leaks keys
https://gofetch.fail/

**Comment by nickfarrow** [comment]
Phoenixd Server
https://twitter.com/PhoenixWallet/status/1771236080680841668

**Comment by nickfarrow** [comment]
xz-utils backdoor would've allowed remote access to almost every linux machine
https://twitter.com/niftynei/status/1774055520246137306

**Comment by nickfarrow** [comment]
Ledger Installer - Setup Ledger without Ledger Live
https://github.com/darosior/ledger_installer

**Comment by iknowwhatyourxPUBdidlastsummer** [comment]
COLDCARD Q1 Address Validation
https://www.nobsbitcoin.com/coldcard-q-firmware-v1-1-0/
