### ISSUE TITLE
November 2024 Meeting Topics

### ISSUE THREAD

**Issue by CicheR** [MelbourneBitDevs/meetup#30]
✍️  Link anything you'd like to discuss: news, demos, ideas, whatever!

₿ :speech_balloon:

🤩🙌

**Comment by CicheR** [comment]
[![Bisq](https://bisq.network/images/bisq-logo.svg)](https://bisq.network/)
##### [A decentralized Bitcoin exchange network](https://bisq.network/)
---
- Discuss Bisq P2P platform
   - Main goals
   - Differentiation points
   - Challenges
   - Trade-offs
- Compare with other similar purpose no-KYC platforms:
   - [Robosats](https://learn.robosats.com)
   - [lnp2pbot.com](https://lnp2pbot.com)

:gear:📺 **_Live trade demo_** (as last time with Robosats 💵🔀₿)

**Comment by BBlackwo** [comment]
Localhost Research Launched to Support Individuals Contributing to Critical Bitcoin Codebases

https://www.nobsbitcoin.com/localhost-research-launched-to-support-individuals-contributing-to-critical-bitcoin-codebases/

**Comment by open-source3** [comment]
[Analyzing Bitcoin Consensus: Risks in Protocol Upgrades](https://www.youtube.com/watch?v=-LGRFZf4JzQ): 
Conversation with Lyn Alden,  delving into the complexities of Bitcoin consensus, exploring the various stakeholders involved in maintaining it, the implications of hard and soft forks, and the importance of understanding the state of mind of stakeholders. They discuss the risks associated with network fragmentation and the potential impact of institutional investors on Bitcoin's future, emphasizing the need for education and awareness within the community. 

Further reading see paper published by Lyn Alden, Ren Crypto Fish, Steve Lee "[Analyzing Bitcoin Consensus: Risks in Protocol Upgrades.](https://github.com/bitcoin-cap/bcap)"

**Comment by open-source3** [comment]
BTC best practice training 101 :-) 
[https://x.com/naiivememe/status/1833484585168244771](https://x.com/naiivememe/status/1833484585168244771)

**Comment by nickfarrow** [comment]
Bitcoin Stack State
https://x.com/t4t5/status/1861066474623782959

**Comment by nickfarrow** [comment]
Localhost Research
https://lclhost.org/

**Comment by nickfarrow** [comment]
US Court Lifts Sanctions on Tornado Cash

https://www.therage.co/fifth-circuit-lifts-tornado-cash-sanctions/

**Comment by nickfarrow** [comment]
Great Script Restoration Interpreter 
https://x.com/n1ckler/status/1854552545084977320

**Comment by nickfarrow** [comment]
DLC Dev Kit
https://x.com/bennyhodl/status/1853909096333754524

**Comment by nickfarrow** [comment]
ColliderScript: Covenants in Bitcoin via 160-bit hash collisions
https://eprint.iacr.org/2024/1802

**Comment by nickfarrow** [comment]
Payment Censorship in the Lightning Network Despite Encrypted Communication
https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.AFT.2024.12

**Comment by nickfarrow** [comment]
Fix broken URLs to lists.linuxfoundation.org
https://github.com/bitcoinops/bitcoinops.github.io/pull/2018
