### ISSUE TITLE
Parkes Bush Bash 2025 Meeting Topics

### ISSUE THREAD

**Issue by BBlackwo** [MelbourneBitDevs/meetup#31]
✍️ Link anything you'd like to discuss: news, demos, ideas, whatever!

**Comment by BBlackwo** [comment]
Localhost Research Launched to Support Individuals Contributing to Critical Bitcoin Codebases

https://www.nobsbitcoin.com/localhost-research-launched-to-support-individuals-contributing-to-critical-bitcoin-codebases/

**Comment by BBlackwo** [comment]
# Vulnerabilities

Cities Skylines II Traffic Mod had a backdoor to steal secrets from Exodus Wallet and bypassed Antivirus
- https://www.paradoxinteractive.com/games/cities-skylines-ii/news/traffic-breach-statement
- [LowLevel Deep Dive Video](https://www.youtube.com/watch?v=VH_8arwuRz8)

Lottie-Player supply chain attack, actors targeted cryptocurrency wallets to steal funds.
- https://securityaffairs.com/170441/hacking/lottiefiles-confirmed-a-supply-chain-attack-on-lottie-player.html

**Comment by BBlackwo** [comment]
Fifth Circuit Lifts Tornado Cash Sanctions

https://www.therage.co/fifth-circuit-lifts-tornado-cash-sanctions/

>The court has found that OFAC overstepped its authority by placing Tornado Cash on OFAC's Specially Designated Nationals and Blocked Persons List, reversing a District Court's ruling upholding Sanctions on the software

**Comment by Kermit21Million** [comment]
Lightning Node Channel Management Best Practices

Discussion on Lightning Node Channel Management and best practices on choosing Node partners, setting fees, balancing channels, software support packages and upcoming improvements to Lightning Node software and enhancements.

**Comment by btcschellingpt** [comment]
BIP352 v BIP47 (and variants) aka: Silent Payments v Paynyms 

Let's explore the differences between the new and the old
BIP352 is brand new with limited support
BIP47 has been around for a while

They use different approaches for sharing secrets between participants
Both clearly work and each has a different set of trade-offs

Background reading at silentpayments.xyz

**Comment by btcschellingpt** [comment]
Growing support for funding bitcoin (and nostr) FOSS projects and developers 
- Initially private/public arrangements between large exchanges and some (fortunate) developers
- A range of charitable-status entities emerging to channel donations and fund FOSS
- Brink, HRF, OpenSats, Maelstrom, 2140 (soon)

How do they work, why are they important and what should we do .. if anything?

https://opensats.org/about
https://hrf.org/program/financial-freedom/bitcoin-development-fund/
https://brink.dev/
https://maelstrom.fund/bitcoin-grant-program/

**Comment by btcschellingpt** [comment]
What is the Liquid sidechain?
- elements open source software that's a fork of Bitcoin Core
- some important differentiations which provide benefits that come with trade-offs
- let's explore key features
- emerging use-cases

https://blockstream.com/liquid/
https://github.com/ElementsProject/elements/releases?ref=blog.blockstream.com

**Comment by BBlackwo** [comment]
Analyzing Bitcoin Consensus: Risks in Protocol Upgrades by Ren Crypto Fish, Steve Lee, and Lyn Alden

https://github.com/bitcoin-cap/bcap/blob/main/bcap_v1.0.pdf

**Comment by BBlackwo** [comment]
# Legal

Bitcoin Fog User Roman Sterlingov Gets 12.5 Years for Allegedly Running It Based on 'Junk Science' 😡 
- https://www.nobsbitcoin.com/bitcoin-fog-user-roman-sterlingov-gets-12-5-years-for-allegedly-running-it-based-on-junk-science/

## On a more positive legal note

Samourai Wallet & Tornado Cash Prosecutor Damian Williams to Step Down in December
- https://www.nobsbitcoin.com/samourai-wallet-tornado-cash-prosecutor-damian-williams-to-step-down-in-december/

Ocean supports Samourai Wallet’s legal defense despite past tensions
- https://atlas21.com/ocean-supports-samourai-wallets-legal-defense-despite-past-tensions/

Fifth Circuit Lifts Tornado Cash Sanctions

- https://www.therage.co/fifth-circuit-lifts-tornado-cash-sanctions/

> The fifth circuit particularly appears to take issue with the fact that "because the software continues to operate regardless of the sanctions, and the blockchain technology “allows peer-to-peer transfers . . . without requiring the recipient to consent to transfer,” some users may become liable whenever someone transfers them digital assets via Tornado Cash, even without their knowledge or consent."

> "These smart contracts must now be removed from the sanctions list and US persons will once again be allowed to use this privacy-protecting protocol. Put another way, the government’s overreach will not stand," [writes](https://x.com/iampaulgrewal/status/1861549060710375562) Coinbase Chief Legal Officer Paul Grewal on X.

**Comment by btcschellingpt** [comment]
Robosats exploring orderbook creation on nostr

Using nostr as a solution component in decentralised system design is super interesting because it may solve a key attack vector because the necessarily shared "view of the world" has previously been centralised. Lots more possibilities for this approach.

https://www.nobsbitcoin.com/robosats-v0-7-2-alpha/

**Comment by aphanley** [comment]
Liana v8.0 Improved Setup Process, New Templates, BitBox02 Support

Liana is a wallet providing support for timelocks and multiple recovery pathways using segwit or taproot miniscript

https://www.nobsbitcoin.com/liana-v8-0/

**Comment by btcschellingpt** [comment]
> Lightning Node Channel Management Best Practices
> 
> Discussion on Lightning Node Channel Management and best practices on choosing Node partners, setting fees, balancing channels, software support packages and upcoming improvements to Lightning Node software and enhancements.

Worth discussing types and purpose of running a sovereign lightning node first!

**Comment by nickfarrow** [comment]
ColliderScript: Covenants in Bitcoin via 160-bit hash collisions
https://eprint.iacr.org/2024/1802

**Comment by nickfarrow** [comment]
Payment Censorship in the Lightning Network Despite Encrypted Communication
https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.AFT.2024.12

**Comment by nickfarrow** [comment]
Great Script Restoration Interpreter
https://x.com/n1ckler/status/1854552545084977320
