### ISSUE TITLE
December 2024 Meeting Topics

### ISSUE THREAD

**Issue by nickfarrow** [MelbourneBitDevs/meetup#32]
Link anything you'd like to discuss: news, demos, ideas, whatever!

**Comment by nickfarrow** [comment]
An unrelated cybercriminal network named MATRIX was taken down
https://matrix.org/blog/2024/12/unrelated-cybercriminal-network-taken-down/

**Comment by nickfarrow** [comment]
Major Vulnerability In WabiSabi Coinjoin Protocol
https://www.therage.co/vulnerability-wabisabi-coinjoin/

**Comment by nickfarrow** [comment]
High Risk - Low Reward: Reflections of a Bitcoin Co-Founder
https://tonygiorgio.com/high-risk-low-reward/

**Comment by BBlackwo** [comment]
Namecheap surpasses $73M in BTC revenue with 1.1m transactions through BTCPay Integration
https://blog.btcpayserver.org/case-study-namecheap/

**Comment by nickfarrow** [comment]
Apparent Wasabi Vulnerability also exists in Samourai
https://x.com/not_nothingmuch/status/1797254556943872290

**Comment by ghost** [comment]
Zeus on Solana validates first bitcoin transactions.
https://medium.com/@zeus-network/milestone-first-bitcoin-transaction-validated-on-solana-39784c624c23

**Comment by BBlackwo** [comment]
Lark: Java based Bitcoin USB Hardware Wallet Interface library

https://github.com/sparrowwallet/lark

**Comment by BBlackwo** [comment]
Samourai Wallet Pretrial Hearing Moved to March 12, Trial Set for November 3, 2025

https://www.therage.co/samourai-wallet-trial-set-for-november-3-2025/

> The postponement is granted in light of additional discovery filed in the case, now totaling 17 Terabytes of data.

**Comment by BBlackwo** [comment]
Researchers Uncover Backdoor in Solana's Popular Web3.js npm Library

https://thehackernews.com/2024/12/researchers-uncover-backdoor-in-solanas.html

**Comment by open-source3** [comment]
“With Ocean… you can put this little package on top of your node and your mining equipment and you can make your own block templates… solving such a BIG [part] of the mining decentralization problem of having a small amount of mining pools deciding what gets into a block.”
[https://x.com/BTCsessions/status/1868989559247081620](https://x.com/BTCsessions/status/1868989559247081620)

**Comment by open-source3** [comment]
Ark Labs batching solution, making self-custodial Bitcoin operations economically viable at scale...making on-chain operations cost-effective:

[https://x.com/bergealex4/status/1868143325024555029](https://x.com/bergealex4/status/1868143325024555029)

**Comment by nickfarrow** [comment]
Alby shutting down shared wallet
https://stacker.news/items/769253

**Comment by nickfarrow** [comment]
Google announces Willow Quantum Chip
https://blog.google/technology/research/google-willow-quantum-chip/

**Comment by nickfarrow** [comment]
More info on Wasabi Vulnerability 
https://github.com/GingerPrivacy/GingerWallet/discussions/116

**Comment by nickfarrow** [comment]
Unprecedented Interception of US Telecommunications
https://www.nbcnews.com/tech/security/us-officials-urge-americans-use-encrypted-apps-cyberattack-rcna182694

Edit: certainly not say unprecedented, but unprecedented Interception by a foreign state!

**Comment by CicheR** [comment]
![image](https://github.com/user-attachments/assets/e49b60ba-604d-4566-ba0f-87b50b470c07)

Containerized:
- Node
- Bisq instance
- Robosats coordinator
  - [Deployment Orchestrations](https://github.com/RoboSats/robosats-deploy)

**Comment by CicheR** [comment]
DeFi on ₿:
- https://sovryn.app/
- https://liquid.net/

**Comment by craigman-1** [comment]
https://keet.io/
Keet by Holepunch
has anyone used this?
